#!/usr/bin/env sh
which home-manager >/dev/null 2>/dev/null && exit 1
[ -f ~/.config/nixpkgs/home.nix ]         && exit 1
set -e
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
nix-shell '<home-manager>' -A install
cp /etc/nixos/home.nix ~/.config/nixpkgs/home.nix
