#!/usr/bin/env bash
set -e

# -------- Sanity checks --------

if [ "$#" -ne 1 ] ; then
    echo "usage: ./format-ext4 <device-to-destroy>" 
    exit 1
fi

WIPE_DEVICE=$1

if mount | grep $WIPE_DEVICE > /dev/null; then
    echo "The device '$WIPE_DEVICE' is already mounted. Action cancelled."
    exit 1
fi

read -p "WARNING! This will DESTROY '$WIPE_DEVICE'! Are you sure? If so, type '$WIPE_DEVICE': " choice
if [ "$choice" != "$WIPE_DEVICE" ]; then
  echo "Action cancelled."
  exit 1
fi

echo "-------- Formatting '$WIPE_DEVICE' --------"

TAG=$(xxd -u -l 8 -p /dev/urandom)
wipefs -a $WIPE_DEVICE
parted -a optimal -s $WIPE_DEVICE -- \
  mklabel gpt \
  mkpart logical 0%      256MiB   set 1 bios_grub on \
  mkpart logical 256MiB  512MiB   set 2 esp on  \
  mkpart logical 512MiB  -9GB \
  mkpart logical -9GB    100% \
  name 1 $TAG-b \
  name 2 $TAG-be \
  name 3 $TAG-r \
  name 4 $TAG-s

mkfs.ext4  -F    -L "boot"     /dev/disk/by-partlabel/$TAG-b
mkfs.vfat  -F 32 -n "BOOT-EFI" /dev/disk/by-partlabel/$TAG-be
mkfs.ext4  -F    -L "root"     /dev/disk/by-partlabel/$TAG-r
mkswap           -L "swap"     /dev/disk/by-partlabel/$TAG-s

echo "-------- Mounting '$WIPE_DEVICE' --------"

mount /dev/disk/by-partlabel/$TAG-r /mnt
mkdir -p /mnt/boot
mount /dev/disk/by-partlabel/$TAG-b /mnt/boot
