#!/usr/bin/env bash
set -e
SCRIPT_PATH=`realpath $0`
SCRIPT_PARENT_PATH=`dirname $SCRIPT_PATH`

# -------- Sanity checks --------

if [ "$#" -ne 1 ] ; then
    echo "usage: setup/format-efi-ext4-enc <device-to-destroy>" 
    exit 1
fi

WIPE_DEVICE=$1

if mount | grep $WIPE_DEVICE > /dev/null; then
    echo "The device '$WIPE_DEVICE' is already mounted. Action cancelled."
    exit 1
fi

read -p "WARNING! This will DESTROY '$WIPE_DEVICE'! Are you sure? If so, type '$WIPE_DEVICE': " choice
if [ "$choice" != "$WIPE_DEVICE" ]; then
  echo "Action cancelled."
  exit 1
fi

echo; echo "-------- Formatting '$WIPE_DEVICE' partitions --------"

# Format the disk
wipefs -a $WIPE_DEVICE
parted -a optimal -s $WIPE_DEVICE -- \
  mklabel gpt \
  mkpart primary 0%      512MiB set 1 esp on \
  mkpart primary 512MiB  100%

# Wait for udev to catch up
sync
udevadm settle

# Import variables that point to disk partitions, etc
. $SCRIPT_PARENT_PATH/util $WIPE_DEVICE

echo; echo "-------- '$WIPE_DEVICE' partitions: --------"
parted $WIPE_DEVICE -- print

echo; echo "-------- Formatting '$WIPE_DEVICE' (filesystems) --------"

cryptsetup -q luksFormat --pbkdf argon2id $ENC_PART_BY_PARTUUID
cryptsetup -q luksOpen $ENC_PART_BY_PARTUUID $ENC
pvcreate /dev/mapper/$ENC
vgcreate $VG /dev/mapper/$ENC
lvcreate -L 8G         -n swap $VG; mkswap       -L "swap" /dev/$VG/swap
lvcreate -l '100%FREE' -n root $VG; mkfs.ext4 -F -L "root" /dev/$VG/root
mkfs.vfat -F 32 $BOOT_PART_BY_PARTUUID

echo; echo "-------- '$WIPE_DEVICE': partition summary --------"
echo "disk $WIPE_DEVICE {"
echo "  partition ${BOOT_PART_BY_PARTUUID}"
echo "  partition ${ENC_PART_BY_PARTUUID} {{"
echo "    luks (/dev/mapper/$ENC) {{"
echo "      volume-group (/dev/$VG) {"
echo "        physical-volume (/dev/$VG/root)"
echo "        physical-volume (/dev/$VG/swap)" 
echo "      }"
echo "    }}"
echo "}"
echo

lsblk --fs $WIPE_DEVICE
echo

echo "-------- Unmapping '$WIPE_DEVICE' --------"
lvchange -an /dev/$VG/swap
lvchange -an /dev/$VG/root
vgchange -an $VG
cryptsetup luksClose $ENC
