#!/usr/bin/env bash
set -e

# -------- Sanity checks --------

if [ ! -f setup/mount ] || [ ! -d /mnt/boot ]; then
    echo "error: first need to run setup/format then setup/mount"
    exit 1
fi

echo "-------- Copying NixOS configuration --------"

nixos-generate-config --root /mnt
cp -r configuration.nix files patches /mnt/etc/nixos/

echo "-------- Updating current OS's packages --------"

# Workaround for https://github.com/NixOS/nixpkgs/issues/126141
nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=/mnt/etc/nixos/configuration.nix 

echo "-------- Installing NixOS --------"

nixos-install --root /mnt
